import = [
    "~/.config/alacritty/themes/themes/everforest_dark.toml"
]
# custom background added background = '#23272A'

[env]
TERM = "xterm-256color"

[window]
padding.x = 6
padding.y = 6

decorations = "Buttonless"

opacity = 1
blur = true

option_as_alt = "Both"


[font]
normal.family = "Hack Nerd Font Mono"
size = 15

offset.x = 0  # For letter spacing (default: 0)
offset.y = 6  # For line spacing (default: 0)

glyph_offset.x = 0
glyph_offset.y = 0

[scrolling]
history = 40000
